### ISSUE TITLE
Краши при повороте экрана

### ISSUE THREAD

**Issue by A-App** [A-App/Music-Strobe#59]
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323) at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341) at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597) at android.app.BackStackRecord.commit(BackStackRecord.java:575) at view.ActivityMain.onConfigurationChanged(Unknown Source) at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4214) at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:4341) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:146) at android.app.ActivityThread.main(ActivityThread.java:5678) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) at dalvik.system.NativeStart.main(Native Method)

**Comment by A-App** [comment]
если выключить экран (при включенном стробе вспышкой) и повернуть, а потом включить.
зависает очень серьезно.

**Comment by A-App** [comment]
при повороте включается кнопка strobe
