### ISSUE TITLE
crash - краш при повороте экрана

### ISSUE THREAD

**Issue by A-App** [A-App/Music-Strobe#66]
duplicate #59
если выключить экран и повертеть, потом включить (однажды было видно 2 фрагмента контролов одновременно)
01-12 12:01:25.456: E/AndroidRuntime(11450): FATAL EXCEPTION: main
01-12 12:01:25.456: E/AndroidRuntime(11450): java.lang.RuntimeException: Unable to stop service today.app.a.amusicstrobe.ServiceNoiseMonitor@42a304c8: java.lang.NullPointerException
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:2787)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at android.app.ActivityThread.access$2100(ActivityThread.java:150)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at android.os.Looper.loop(Looper.java:137)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at android.app.ActivityThread.main(ActivityThread.java:5279)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at dalvik.system.NativeStart.main(Native Method)
01-12 12:01:25.456: E/AndroidRuntime(11450): Caused by: java.lang.NullPointerException
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at today.app.a.amusicstrobe.ServiceNoiseMonitor.onDestroy(ServiceNoiseMonitor.java:87)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:2770)
01-12 12:01:25.456: E/AndroidRuntime(11450): 	... 10 more

**Comment by A-App** [comment]
01-12 12:01:25.456: E/AndroidRuntime(11450): Caused by: java.lang.NullPointerException
01-12 12:01:25.456: E/AndroidRuntime(11450): 	at today.app.a.amusicstrobe.ServiceNoiseMonitor.onDestroy(ServiceNoiseMonitor.java:87)

здесь:	app.getAdsAndAnalytics().sendException(e); (т.е. теряется app)? возможно, перегрузка памяти?

**Comment by A-App** [comment]
это то же что #59
а перед этим:

01-12 15:48:43.955: E/AndroidRuntime(26764): FATAL EXCEPTION: main
01-12 15:48:43.955: E/AndroidRuntime(26764): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1336)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1347)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.BackStackRecord.commit(BackStackRecord.java:574)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at view.ActivityMain.setFragmentControlsOrientation(ActivityMain.java:337)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at view.ActivityMain.onConfigurationChanged(ActivityMain.java:322)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:3911)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:3870)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:4128)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.os.Looper.loop(Looper.java:137)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at android.app.ActivityThread.main(ActivityThread.java:5279)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
01-12 15:48:43.955: E/AndroidRuntime(26764): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by A-App** [comment]
после try-catch вспышка работает, но при попытке resume активити - новый краш:
01-12 16:06:26.011: E/AndroidRuntime(30082): FATAL EXCEPTION: main
01-12 16:06:26.011: E/AndroidRuntime(30082): java.lang.RuntimeException: Unable to resume activity {today.app.a.amusicstrobe/view.ActivityMain}: java.lang.NullPointerException
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2826)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2855)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.os.Looper.loop(Looper.java:137)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.app.ActivityThread.main(ActivityThread.java:5279)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at dalvik.system.NativeStart.main(Native Method)
01-12 16:06:26.011: E/AndroidRuntime(30082): Caused by: java.lang.NullPointerException
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at view.ActivityMain.registerStrobeReceiver(ActivityMain.java:230)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at view.ActivityMain.onResume(ActivityMain.java:270)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1202)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.app.Activity.performResume(Activity.java:5345)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2816)
01-12 16:06:26.011: E/AndroidRuntime(30082): 	... 10 more
